name: 'Update snap tag'
description: 'Update the snapcraft.yaml for a given snap with the latest upstream tag'
inputs:
  repo:
    description: 'The repo containing the snapcraft.yaml to be updated'
    required: true
    default: 'None'
outputs:
  new-snapcraft-yaml:
    description: "Updated snapcraft.yaml"
    value: ${{ steps.updatesnapyaml.outputs.new-snapcraft-yaml }}
runs:
  using: "composite"
  steps:
    - id: updatesnapyaml
      run: echo "new-snapcraft-yaml=$(./updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token ${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/${{ github.repository }} > snapcraft.yaml)" >> $GITHUB_OUTPUT
      shell: bash
