name: 'Update snap tag'
description: 'Update the snapcraft.yaml for a given snap with the latest upstream tag'
inputs:
  token:
    description: 'A Github PAT'
    required: true
  repo:
    description: 'The repo containing the snapcraft.yaml to be updated'
    required: true
    default: 'None'
outputs:
  new-snapcraft-yaml:
    description: "Updated snapcraft.yaml"
    value: ${{ steps.updatesnapyaml.outputs.new-snapcraft-yaml }}
runs:
  using: "composite"
  steps:
    - name: checkout desktop-snaps repo
      uses: actions/checkout@v3
      with:
        repository: 'ubuntu/desktop-snaps'
        ref: add-action
        path: desktop-snaps
    - id: updatesnapyaml
      run: |
        echo "new-snapcraft-yaml=$(./desktop-snaps/updatesnap/updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://api.github.com/repos/${{ github.repository }} > snapcraft.yaml)" >> $GITHUB_OUTPUT
      env:
        GITHUB_USER: ubuntu
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
